-- 각 연도별 군집 크기의 편차를 계산하는 쿼리
SELECT 
    YEAR(DIFFERENTIATION_DATE) as YEAR,
    (
        SELECT MAX(SIZE_OF_COLONY)
        FROM ECOLI_DATA ed2
        WHERE YEAR(ed2.DIFFERENTIATION_DATE) = YEAR(ed1.DIFFERENTIATION_DATE)
    ) - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM ECOLI_DATA ed1
ORDER BY YEAR, YEAR_DEV;