-- 코드를 입력하세요
SELECT A.CATEGORY, B.MAX_PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT A
JOIN (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE FROM FOOD_PRODUCT GROUP BY CATEGORY) B
    ON A.CATEGORY = B.CATEGORY AND A.PRICE = B.MAX_PRICE
WHERE A.CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY A.CATEGORY
ORDER BY MAX_PRICE DESC;

-- SELECT A.CATEGORY,  A.PRICE,    A.PRODUCT_NAME
# FROM FOOD_PRODUCT A
# INNER JOIN(
#             SELECT CATEGORY,MAX(PRICE) AS MAX_PRICE
#             FROM FOOD_PRODUCT 
#             GROUP BY CATEGORY
#           ) B
#           ON  A.CATEGORY = B.CATEGORY
#           AND A.PRICE = B.MAX_PRICE
# WHERE A.CATEGORY IN ('과자', '국', '김치', '식용유')
# ORDER BY A.PRICE DESC
